/* Copyright (c) 2026 Alexandre J. Raymond <ajraymond@septentris.com>
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "test-debug-common.h"
#include "simde/simde-arch.h"
#include "test/test.h"

static int
test_simde_diagnostic_arch(SIMDE_MUNIT_TEST_ARGS) {

  PRINT_SECTION("ARCH");
    PRINT_DEFINE_VALUE(SIMDE_ARCH_AARCH64);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ALPHA);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_AMD64);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_AVR);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_BLACKFIN);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_CONVEX);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_CRIS);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_E2K);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_EPIPHANY);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_FRV);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_H8300);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_HPPA);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_IA64);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_LOONGARCH);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_M32R);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_M68K);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_MICROBLAZE);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_MIPS);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_MN10300);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_POWER);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV32);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV64);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_SPARC);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_SUPERH);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_TMS320);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_XTENSA);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_WASM);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ZARCH);
  PRINT_SECTION_END();

  PRINT_SECTION("ARM");
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_NEON);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_AES);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_COMPLEX);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_CRC32);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_CRYPTO);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_DOTPROD);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_FMA);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_FP16_FML);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_FRINT);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_MATMUL_INT8);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_NEON_BF16);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_NEON_FP16);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_QRDMX);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_SHA2);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_SHA3);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_SHA512);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_SM3);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_SM4);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_SVE);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_SVE2);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ARM_SVE2_BITPERM);
  PRINT_SECTION_END();

  PRINT_SECTION("LOONGARCH");
    PRINT_DEFINE_VALUE(SIMDE_ARCH_LOONGARCH_LSX);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_LOONGARCH_LASX);
  PRINT_SECTION_END();

  PRINT_SECTION("MIPS");
    PRINT_DEFINE_VALUE(SIMDE_ARCH_MIPS_LOONGSON_MMI);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_MIPS_MSA);
  PRINT_SECTION_END();


  PRINT_SECTION("POWER");
    PRINT_DEFINE_VALUE(SIMDE_ARCH_POWER_ALTIVEC);
  PRINT_SECTION_END();

  PRINT_SECTION("RISCV");
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV_ZVE32X);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV_ZVE32F);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV_ZVE64X);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV_ZVE64F);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV_ZVE64D);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV_V);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV_ZVFH);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_RISCV_ZVFHMIN);
  PRINT_SECTION_END();

  PRINT_SECTION("WASM");
    PRINT_DEFINE_VALUE(SIMDE_ARCH_WASM_SIMD128);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_WASM_RELAXED_SIMD);
  PRINT_SECTION_END();

  PRINT_SECTION("X86");
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AES);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX2);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512BITALG);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512BW);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512VBMI);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512VBMI2);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512VNNI);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX5124VNNIW);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512VP2INTERSECT);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512VPOPCNTDQ);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512BF16);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512CD);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512DQ);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512F);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512VL);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_AVX512FP16);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_BMI1);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_BMI2);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_F16C);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_FMA);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_GFNI);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_MMX);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_PCLMUL);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_SSE);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_SSE2);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_SSE3);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_SSSE3);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_SSE4_1);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_SSE4_2);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_VPCLMULQDQ);
    PRINT_DEFINE_VALUE(SIMDE_ARCH_X86_XOP);
  PRINT_SECTION_END();

  PRINT_SECTION("ZARCH");
    PRINT_DEFINE_VALUE(SIMDE_ARCH_ZARCH_ZVECTOR);
  PRINT_SECTION_END();

  return 0;
}

SIMDE_TEST_FUNC_LIST_BEGIN
  SIMDE_TEST_FUNC_LIST_ENTRY(diagnostic_arch)
SIMDE_TEST_FUNC_LIST_END

#include <test/debug/test-debug-footer.h>
