/* Copyright (c) 2026 Alexandre J. Raymond <ajraymond@septentris.com>
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "test-debug-common.h"
#include "simde/simde-common.h"
#include "test/test.h"

#define SIMDE_TESTS_CURRENT_ISAX simde-common

static int
test_simde_diagnostic_common(SIMDE_MUNIT_TEST_ARGS) {

  PRINT_SECTION("BUG GCC");
      PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_100760);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_100761);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_100762);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_100927);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_101614);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_105339);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_111609);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_113065);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_114521);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_53784);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_87467);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_91341);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_92035);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_94482);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_94488);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_95144);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_95227);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_95399);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_95471);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_95483);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_95782);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_96174);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_97248);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_98521);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_ARM_SHIFT_SCALAR);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_BAD_MM_EXTRACT_EPI8);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_BAD_MM_SRA_EPI32);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_BAD_VEXT_REV32);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_REV_208793);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_REV_247851);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_REV_260989);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_REV_264019);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_REV_274313);
    PRINT_DEFINE_VALUE(SIMDE_BUG_GCC_SIZEOF_IMMEDIATE);
  PRINT_SECTION_END();

  PRINT_SECTION("BUG CLANG");
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_44589);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_45541);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_45931);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_46770);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_46840);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_46844);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_48257);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_48673);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_50893);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_50901);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_50932);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_60655);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_71362);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_71365);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_71751);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_71763);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_BAD_MADD);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_BAD_VGET_SET_LANE_TYPES);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_BAD_VI64_OPS);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_GIT_4EC445B8);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_POWER9_16x4_BAD_SHIFT);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_REV_234560);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_REV_298042);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_REV_299346);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_REV_344862);
    PRINT_DEFINE_VALUE(SIMDE_BUG_CLANG_REV_365298);
  PRINT_SECTION_END();

  PRINT_SECTION("BUG INTEL");
    PRINT_DEFINE_VALUE(SIMDE_BUG_INTEL_857088);
  PRINT_SECTION_END();

  PRINT_SECTION("BUG MCST");
    PRINT_DEFINE_VALUE(SIMDE_BUG_MCST_LCC_FMA_WRONG_RESULT);
    PRINT_DEFINE_VALUE(SIMDE_BUG_MCST_LCC_MISSING_AVX_LOAD_STORE_M128_FUNCS);
    PRINT_DEFINE_VALUE(SIMDE_BUG_MCST_LCC_MISSING_CMOV_M256);
  PRINT_SECTION_END();

  PRINT_SECTION("BUG MSVC");
    PRINT_DEFINE_VALUE(SIMDE_BUG_MSVC_ROUND_EXTRACT);
  PRINT_SECTION_END();

  PRINT_SECTION("BUG PGI");
    PRINT_DEFINE_VALUE(SIMDE_BUG_PGI_30104);
    PRINT_DEFINE_VALUE(SIMDE_BUG_PGI_30106);
    PRINT_DEFINE_VALUE(SIMDE_BUG_PGI_30107);
  PRINT_SECTION_END();

  PRINT_SECTION("BUG VEC");
    PRINT_DEFINE_VALUE(SIMDE_BUG_VEC_CPSGN_REVERSED_ARGS);
  PRINT_SECTION_END();

  return 0;
}

SIMDE_TEST_FUNC_LIST_BEGIN
  SIMDE_TEST_FUNC_LIST_ENTRY(diagnostic_common)
SIMDE_TEST_FUNC_LIST_END

#include <test/debug/test-debug-footer.h>
